/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BusinessHour = IDL.Record({ 'day' : IDL.Text, 'time' : IDL.Text });
export const ClinicInfo = IDL.Record({
  'about' : IDL.Text,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'instagramUrl' : IDL.Text,
  'googleMapsUrl' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'address' : IDL.Text,
  'specialization' : IDL.Text,
  'doctorName' : IDL.Text,
  'contactNumbers' : IDL.Vec(IDL.Text),
});
export const Service = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'review' : IDL.Text,
  'date' : IDL.Text,
  'patientName' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getBusinessHours' : IDL.Func([], [IDL.Vec(BusinessHour)], ['query']),
  'getClinicInfo' : IDL.Func([], [ClinicInfo], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BusinessHour = IDL.Record({ 'day' : IDL.Text, 'time' : IDL.Text });
  const ClinicInfo = IDL.Record({
    'about' : IDL.Text,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'instagramUrl' : IDL.Text,
    'googleMapsUrl' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'address' : IDL.Text,
    'specialization' : IDL.Text,
    'doctorName' : IDL.Text,
    'contactNumbers' : IDL.Vec(IDL.Text),
  });
  const Service = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'review' : IDL.Text,
    'date' : IDL.Text,
    'patientName' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'getBusinessHours' : IDL.Func([], [IDL.Vec(BusinessHour)], ['query']),
    'getClinicInfo' : IDL.Func([], [ClinicInfo], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };